apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello-app
spec:
  components:
    - name: hello-kubernetes
      type: frontend
      properties:
        name: hello-kubernetes
        image: httpd:latest
        port: 80
